repos:
  - repo: local
    hooks:
        - id: copyright-headers
          name: copyright-headers
          language: python
          files: \.(c|h|cpp|hpp|cc|cxx|m|mm|inc|java|gd)$
          entry: python3 ls.github/copyright_headers.py
          exclude: >-
            (?x)^(
              .*thirdparty.*|
              addons/vrm.*|
              addons/godot_state_charts.*|
              addons/xr_vignette.*|
              addons/unidot_importer.*|
              addons/Godot-MToon-Shader.*|
              addons/gut.*|
              addons/smoothing.*|
              addons/godot-xr-tools.*|
              addons/unidot.*
            )
